DROP TABLE IF EXISTS clinic CASCADE;
DROP TABLE IF EXISTS donor CASCADE;
DROP TABLE IF EXISTS operation;
DROP TABLE IF EXISTS organ CASCADE;
DROP TABLE IF EXISTS recipient CASCADE;
DROP TABLE IF EXISTS surgeon CASCADE;